version: '3.8'

services:
  canopy-crawler:
    build: .
    container_name: canopy-web-crawler
    volumes:
      # Mount crawl data to persist outside container
      - ./crawl_data:/app/crawl_data
      # Optional: mount config for easy changes
      - ./main.py:/app/main.py
    environment:
      - PYTHONUNBUFFERED=1
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Restart policy
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for future queue-based crawling
  # redis:
  #   image: redis:7-alpine
  #   container_name: canopy-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped

# volumes:
#   redis-data: